// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffhetchigtygaxflurcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmaGV0Y2hpZ3R5Z2F4Zmx1cmNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTQzMzQsImV4cCI6MjA3NDEzMDMzNH0.7t5BGWrrBdP3LUfo1Co9peKLPeaa3zexUEv5wDSdgmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});